### ISSUE TITLE
turn off react/prop-types for typescript files

### ISSUE THREAD

**Issue by TkDodo** [pmedianetwork/eslint-config#16]
Inheriting Props from will throw false positives, e.g.:

```javascript
type LocalProps = { title: string }
const Component: React.StatelessComponent<LocalProps> = ({ children, title }) => ( <div title={title}>{children}</div>)
```

`React.StatelessComponent` defines `Props` as `P & { children?: ReactNode }`, which means `children` is implicitly added. The eslint rules does not grasp that.

Further, that rule doesn't add anything that the ts compiler won't find anyways :)

@namjul @vlabs

**Comment by georggrubner** [comment]
will be done in #15
