### ISSUE TITLE
disable react/no-did-mount-set-state

### ISSUE THREAD

**Issue by namjul** [pmedianetwork/eslint-config#19]
Its already disable in newer versions of airbnb eslint config:
https://github.com/airbnb/javascript/issues/684
Official docs say its okay to use:
https://reactjs.org/docs/react-component.html#componentdidmount

**Comment by TkDodo** [comment]
- since `v3`, we use eslint-config-airbnb v17
- we won't write new class components anyways, as we should use `hooks`.

so this can be closed
