### ISSUE TITLE
update eslint-plugin-react

### ISSUE THREAD

**Issue by TkDodo** [pmedianetwork/eslint-config#20]
because it crashes sometimes with flow annotations.

if you do, revert this commit in insights when updating:

https://github.com/pmedianetwork/adverity/commit/c76e2d843459372db1d63cab463081883d92a7f3

**Comment by danielbartsch** [comment]
this commit in insights led to many new eslint errors. I already reverted that commit.

When we update this package, we must be aware that there will be many new eslint errors, some of which might look wrong to us.

Example: props are defined for a component, but not used in the component directly, but in hocs for it.

**Comment by danielbartsch** [comment]
put it to a new issue: https://github.com/pmedianetwork/adverity/issues/9631#issue-399707894
