### ISSUE TITLE
Add import/extentions to typescript.js

### ISSUE THREAD

**Issue by namjul** [pmedianetwork/eslint-config#24]
---
PR: https://github.com/pmedianetwork/eslint-config/pull/33

---

```        
"import/extensions": [{
            "js": "never",
            "ts": "never",
            "tsx": "never"
        }]
```

**Comment by danielbartsch** [comment]
what does this mean and what changes does this mean for developers?

**Comment by namjul** [comment]
It means we can remove this part from datatap and design-system and have it organized by eslint-config
