### ISSUE TITLE
turn off react/no-unused-prop-types

### ISSUE THREAD

**Issue by georggrubner** [pmedianetwork/eslint-config#27]
**About**

we want to turn off the rule `react/no-unused-prop-types` for two reasons
- flow or typescript do the same out of the box
- it does not work correctly in some cases

this would also increase the developer experience

**Tasks**
- [ ] remove rule `react/no-unused-prop-types`

**Comment by TkDodo** [comment]
Issue moved to [pmedianetwork/adverity-frontend-monorepo #1238](https://github.com/pmedianetwork/adverity-frontend-monorepo/issues/1238) via [**ZenHub**](https://www.zenhub.com/)
