### ISSUE TITLE
Allow ternary in no-unused-expressions

### ISSUE THREAD

**Issue by namjul** [pmedianetwork/eslint-config#31]
---
PR: https://github.com/pmedianetwork/eslint-config/pull/33

---

https://eslint.org/docs/rules/no-unused-expressions#allowternary

**Comment by danielbartsch** [comment]
I think I get the reason why we want this, but can you please provide an explanation?

**Comment by namjul** [comment]
Its a beautiful way to write this kind of code:
```
obj.something ? obj.show() : obj.hide()
```
instead of
```
if(obj.something) {
  return obj.show()
} else {
 obj.hide()
}
```

the difference is that the top returns the value from the called function and the bottom not. Which is why eslint cries but i think its fine for ternary. 

**extra**:
We could also remove the no-void rule than we could do something like this.
```
void obj.something ? obj.show() : obj.hide()
```
This way we tell it that it should always return undefined no matter what the functions do. This would then work even with the `no-unsed-expressions` rule  as it is now.
