### ISSUE TITLE
disallow the use of enums in typescript

### ISSUE THREAD

**Issue by TkDodo** [pmedianetwork/eslint-config#34]
don't: 

```
enum Direction {
  Up,
  Down,
  Left,
  Right,
}
```

do: 
```
type Direction = "up" | "down" | "left" | "right"
```

we could enforce this by enabling:

```
{
  "rules": {
    "no-restricted-syntax": [
      "error",
      {
        "selector": "TSEnumDeclaration",
        "message": "Don't declare enums"
      }
    ]
  }
}
```

but there is also a rule proposal open in the `typescrit-eslint` repo: https://github.com/typescript-eslint/typescript-eslint/issues/561

**Comment by woles** [comment]
what about:

    enum Direction {
        Up = 'up',
        Down = 'down',
        Left = 'left',
        Right = 'right',
    }

for me, this is a very useful thing. 
 - you don't have some hardcoded strings in code,
 - everything in one place
 - easy change

**Comment by TkDodo** [comment]
- It is the same syntax as in `flow`, making it easier for developers to switch context (between `insights` and `datatap` / `presense`)
- Output generated by typescript is pretty verbose.
  - `const enums` would be better, but are not supported by `babel` (which we use).
 - this does not type error
```
enum Direction {
  Up = 1,
  Down = 2,
  Left = 3,
  Right = 4
}

const move = (direction: Direction) => void 0

move(27)
```

see: http://www.typescriptlang.org/play/?ssl=10&ssc=9&pln=1&pc=1#code/KYOwrgtgBAIglgJ2AYwC5wPYigbwFBRQCqADlALxQCMANAbBgO7aUBMdhAMsAGaoVQAzBygAlOAHMAFv0oAWPAF88eZFgDO-CBgBuwAQAoAJohTosALlim0mEAEoKAPig6McI1AAMK7XoOsAOz2eEA

it does however error with union types:
http://www.typescriptlang.org/play/?ssl=10&ssc=2&pln=3&pc=1#code/C4TwDgpgBAIglgJwgY2HA9gOygXigRigB8oAmYqAZgoBYAoO5LAZ2CgFt0A3aPACgAmiFGiwAuWMNQZMASlwA+KF3RwBUAAwNOPPqQDssoA
