### ISSUE TITLE
ban-ts-ignore

### ISSUE THREAD

**Issue by TkDodo** [pmedianetwork/eslint-config#54]
Turn on https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/ban-ts-ignore.md

We don't want to `@ts-ignore`, ever.

**Comment by frycz** [comment]
@TkDodo I have changes for it but first I would upgrade `react-select` to get rid of https://github.com/pmedianetwork/adverity-datatap/blob/7cfb7c72d645a1202c36de3739fbdd7801232db5/web-app/components/TreeSelect/index.tsx#L37 What do you think? The library fix should be there (https://github.com/JedWatson/react-select/pull/3154)
This is actually the only usage of `ts-ignore` I found in Adverity projects (I might missed some:-))

**Comment by TkDodo** [comment]
> This is actually the only usage of ts-ignore I found in Adverity projects (I might missed some:-))

I thought there were no usages at all :)

If it's a minor upgrade, we can definitely do it. And its not blocking this issue from being implemented in `esling-config`. The issue that upgrades eslint-config to that version in datatap has to take care of that.
