### ISSUE TITLE
no-private-imports

### ISSUE THREAD

**Issue by TkDodo** [pmedianetwork/eslint-config#66]
Every feature / component has a "public" interface: It's `index` file. When using a component / a feature, we should _only_ import from that public interface.

However, many features / components have "private" utils / types / hooks. They should be used internally only. If we need them somewhere else, we should move it up. See also: http://handbook.adverity.net/tech-manifest/#utils-types-and-hooks

**Possible implementation**

We could make the directories which this rule should be invoked on customizable to avoid false positives:

```
"no-private-imports": ["error", { "directories": ["features", "components"] } ]
```

This would disallow private imports from `features` or `components`. I think the implementation is rather trivial: Given that we know the importPath, we should error if:

```
directories.some(importPath.startsWith) && importPath.split('/').length > 2
```

Basically, if there is more than one `/` in the path, we are _not_ importing from the public interface:

```
features
  featureA
    index.tsx
    utils.ts
    components
        componentA.tsx
  featureB
```

if `featureB` wants to import from `featureA`:

✅ 
```
import { featureA } from 'features/featureA'
```

❌ 
```
import { fooUtil } from 'features/featureA/utils'
import { fooComponent } from 'features/featureA/components/componentA'
```

So the check for more than one `/` should suffice.

Note that while you are in `featureA`, it is _also_ forbidden to import absolutely from `featureA`:

❌ 
```
import { fooUtil } from 'features/featureA/utils'
```

✅ 
```
import { fooUtil } from './utils'
```

This will also be caught by the rule `no-absolute-internal-imports`

@adamgajzlerowicz what do you think?

**Comment by TkDodo** [comment]
We could also add `utils` and `hooks` to the list - I think it applies there as well. It does not apply to the `store` directory though I think ...

**Comment by adamgajzlerowicz** [comment]
I like it :)

I'd like to finish working on what I have currently in progress first if that is ok - after we can add more rules to it!
