### ISSUE TITLE
Add tests and lint to pipelines

### ISSUE THREAD

**Issue by adamgajzlerowicz** [pmedianetwork/eslint-config#68]
On pr we should check quality of the code by runing 

`npm run test` and `npm run lint`

https://github.com/pmedianetwork/eslint-config/pull/67#issuecomment-598608828

**Comment by TkDodo** [comment]
Issue moved to [pmedianetwork/adverity-frontend-monorepo #1234](https://github.com/pmedianetwork/adverity-frontend-monorepo/issues/1234) via [**ZenHub**](https://www.zenhub.com/)
