### ISSUE TITLE
enable import/no-unused-modules

### ISSUE THREAD

**Issue by TkDodo** [pmedianetwork/eslint-config#74]
unused exports are not always a problem, but they sometimes are. See this commit for an issue it caused: 
https://github.com/pmedianetwork/adverity/pull/11348/commits/cfdbbe456e3cdbe7b81b9ea39e5f439e20ac3dbb

but unused exports are always unnecessary and they increase the mental overhead for developers, as you have to search for usages when changing it (or you don't dare to change them). local consts however are easier to grasp.

see https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-unused-modules.md for config options

**Comment by TkDodo** [comment]
There seem to be issues with typescript though: https://github.com/typescript-eslint/typescript-eslint/issues/371

**Comment by danielbartsch** [comment]
this eslint rule wouldn't have prevented the issue linked.
As the exported function was still imported, even if it was not intended
(with `import * as allTheExports from 'thePath'`)

**Comment by TkDodo** [comment]
> this eslint rule wouldn't have prevented the issue linked.
> As the exported function was still imported, even if it was not intended
> (with `import * as allTheExports from 'thePath'`)

yes, that's true :/

**Comment by TkDodo** [comment]
the typescript issue is still open, and unused exports are not enough of an issue to warrant doing something here. There are much more important things we need to tackle. closing
