### ISSUE TITLE
disable react/jsx-props-no-spreading rule

### ISSUE THREAD

**Issue by patryksuchowierski** [pmedianetwork/eslint-config#80]
After updating `eslint-config-airbnb` to version 18, `react/jsx-props-no-spreading` rule got enabled by default. Atm, within Datatap, it's got overriden locally. There's a need to have that turned off by default at a global level, within eslint-config package

Rule `react/state-in-constructor` got also enabled within aribnb config v18 update.

Current setting within datatap:
```
"react/jsx-props-no-spreading": "off", 
"react/state-in-constructor": ["error", "never"]
```

Analysis:
We should add the above to the `recommended.js` config

**Comment by adamgajzlerowicz** [comment]
This is now done with release `4.4.0`
