### ISSUE TITLE
Ignore packages for `import/extensions`

### ISSUE THREAD

**Issue by bebraw** [pmedianetwork/eslint-config#81]
Since the extensions used within npm packages doesn't matter for applications, we should disable the default behavior like this:

```
"import/extensions": ["error", "ignorePackages"],
```

**Comment by TkDodo** [comment]
@bebraw we currently have this setting:

```
        'import/extensions': [
            'error',
            'always',
            {
                js: 'never',
                ts: 'never',
                tsx: 'never',
            },
        ],
```

would it not be enough to add `mjs` to the list of `nevers`, or how would `ignorePackages` integrate with this config?

**Comment by bebraw** [comment]
@TkDodo With `"ignorePackages"`, it's the second parameter you would have to change.

It's possible adding `mjs` to the list would work as well but it's better you validate that before changing.
